In [1]:
import numpy as np
import pandas as pd

In [2]:
# read data
data_dir = 'data'
df = pd.read_csv(f'{data_dir}/movies_metadata.csv', low_memory=False)
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
# transpose DF to inspect all columns
df.T

,0,1,2,3,4,5,6,7,8,9,...,45456,45457,45458,45459,45460,45461,45462,45463,45464,45465
adult,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', ...",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",NaN,"{'id': 96871, 'name': 'Father of the Bride Col...",NaN,NaN,NaN,NaN,"{'id': 645, 'name': 'James Bond Collection', '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
budget,30000000,65000000,0,16000000,0,60000000,58000000,0,35000000,58000000,...,0,0,0,0,0,0,0,0,0,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",...,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...","[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...","[{'id': 27, 'name': 'Horror'}]","[{'id': 878, 'name': 'Science Fiction'}]","[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'id': 18, 'name': 'Drama'}]","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",[],[]
homepage,http://toystory.disney.com/toy-story,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mgm.com/view/movie/757/Goldeneye/,...,NaN,NaN,NaN,NaN,NaN,http://www.imdb.com/title/tt6209470/,NaN,NaN,NaN,NaN
id,862,8844,15602,31357,11862,949,11860,45325,9091,710,...,84419,390959,289923,222848,30840,439050,111109,67758,227506,461257
imdb_id,tt0114709,tt0113497,tt0113228,tt0114885,tt0113041,tt0113277,tt0114319,tt0112302,tt0114576,tt0113189,...,tt0038621,tt0265736,tt0252966,tt0112613,tt0102797,tt6209470,tt2028550,tt0303758,tt0008536,tt6980792
original_language,en,en,en,en,en,en,en,en,en,en,...,en,en,en,en,en,fa,tl,en,en,en
original_title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,رگ خواب,Siglo ng Pagluluwal,Betrayal,Satana likuyushchiy,Queerama
overview,"Led by Woody, Andy's toys live happily in his ...",When siblings Judy and Peter discover an encha...,A family wedding reignites the ancient feud be...,"Cheated on, mistreated and stepped on, the wom...",Just when George Banks has recovered from his ...,"Obsessive master thief, Neil McCauley leads a ...",An ugly duckling having undergone a remarkable...,"A mischievous young boy, Tom Sawyer, witnesses...",International action superstar Jean Claude Van...,James Bond must unmask the mysterious head of ...,...,An unsuccessful sculptor saves a madman named ...,"In this true-crime documentary, we delve into ...",A film archivist revisits the story of Rustin ...,It's the year 3000 AD. The world's most danger...,"Yet another version of the classic epic, with ...",Rising and falling between a man and woman.,An artist struggles to finish his work while a...,"When one of her hits goes wrong, a professiona...","In a small town live two brothers, one a minis...",50 years after decriminalisation of homosexual...
popularity,21.946943,17.015539,11.7129,3.859495,8.387519,17.924927,6.677277,2.561161,5.23158,14.686036,...,0.222814,0.076061,0.38645,0.661558,5.683753,0.072051,0.178241,0.903007,0.003503,0.163015
poster_path,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,/e64sOI48hQXyru7naBFyssKFxVd.jpg,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,...,/yMnq9mL5uYxbRgwKqyz1cVGCJYJ.jpg,/q75tCM4pFmUzdCg0gqcOQquCaYf.jpg,/lXtoHVdej6kS1Dc7KAhw05sMos9.jpg,/4lF9LH0b0Z1X94xGK9IOzqEW6k1.jpg,/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
production_companies,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'name': 'United Artists', 'id': 60}, {'name'...",...,"[{'name': 'Universal Pictures', 'id': 33}]",[],"[{'name': 'Neptune Salad Entertainment', 'id':...","[{'name': 'Concorde-New Horizons', 'id': 4688}]","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",[],"[{'name': 'Sine Olivia', 'id': 19653}]","[{'name': 'American World Pictures', 'id': 6165}]","[{'name': 'Yermoliev', 'id': 88753}]",[]
production_countries,"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",[],"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...","[{'iso_3166_1': 'IR', 'name': 'Iran'}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'RU', 'name': 'Russia'}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]"
release_date,1995-10-30,1995-12-15,1995-12-22,1995-12-22,1995-02-10,1995-12-15,1995-12-15,1995-12-22,1995-12-22,1995-11-16,...,1946-03-29,2000-10-22,2000-10-03,1995-01-01,1991-05-13,NaN,2011-11-17,2003-08-01,1917-10-21,2017-06-09
revenue,3.73554e+08,2.62797e+08,0,8.14522e+07,7.65789e+07,1.87437e+08,0,0,6.43502e+07,3.52194e+08,...,0,0,0,0,0,0,0,0,0,0
runtime,81,104,101,127,106,170,127,97,106,130,...,65,45,30,85,104,90,360,90,87,75
spoken_languages,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'fa', 'name': 'فارسی'}]","[{'iso_639_1': 'tl', 'name': ''}]","[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'iso_639_1': 'en', 'name': 'English'}]"
status,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released,...,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released
tagline,NaN,Roll the dice and unleash the excitement!,Still Yelling. Still Fighting. Still Ready for...,Friends are the people who let you be yourself...,Just When His World Is Back To Normal... He's ...,A Los Angeles Crime Saga,You are cordially invited to the most surprisi...,The Original Bad Boys.,Terror goes into overtime.,No limits. No fears. No substitutes.,...,Meet...The CREEPER!,NaN,"Do you know what happened 50 years before ""The...",NaN,NaN,Rising and falling between a man and woman,NaN,A deadly game of wits.,NaN,NaN
title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,Subdue,Century of Birthing,Betrayal,Satan Triumphant,Queerama
video,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
vote_average,7.7,6.9,6.5,6.1,5.7,7.7,6.2,5.4,5.5,6.6,...,6.3,7,7,3.5,5.7,4,9,3.8,0,0
vote_count,5415,2413,92,34,173,1886,141,45,174,1194,...,8,2,1,1,26,1,3,6,0,0

In [4]:
df.isna().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [5]:
# fillna for title and overview
df.loc[:,['title','overview']] =  df.loc[:,['title','overview']].fillna('')
df.isna().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                     0
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        0
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [6]:
df['title']

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3                  Waiting to Exhale
4        Father of the Bride Part II
                    ...
45461                         Subdue
45462            Century of Birthing
45463                       Betrayal
45464               Satan Triumphant
45465                       Queerama
Name: title, Length: 45466, dtype: object

In [7]:
df['overview']

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
45461          Rising and falling between a man and woman.
45462    An artist struggles to finish his work while a...
45463    When one of her hits goes wrong, a professiona...
45464    In a small town live two brothers, one a minis...
45465    50 years after decriminalisation of homosexual...
Name: overview, Length: 45466, dtype: object

In [8]:
import re
def get_title_overviews(df):    
    # extract titles and overviews
    title_overviews = df.apply(lambda x:x['title'].lower() +' '+ x['overview'].lower(), axis=1).values
        
    # text cleaning
    title_overviews = [re.sub(r'[^a-zA-Z ]+', ' ', title_overview ) for title_overview in  title_overviews]
    
    # split to list
    title_overviews = [title_overview.split(' ') for title_overview in  title_overviews]
    
    return title_overviews
title_overviews = get_title_overviews(df)
title_overviews[:5]

[['toy',
  'story',
  'led',
  'by',
  'woody',
  '',
  'andy',
  's',
  'toys',
  'live',
  'happily',
  'in',
  'his',
  'room',
  'until',
  'andy',
  's',
  'birthday',
  'brings',
  'buzz',
  'lightyear',
  'onto',
  'the',
  'scene',
  '',
  'afraid',
  'of',
  'losing',
  'his',
  'place',
  'in',
  'andy',
  's',
  'heart',
  '',
  'woody',
  'plots',
  'against',
  'buzz',
  '',
  'but',
  'when',
  'circumstances',
  'separate',
  'buzz',
  'and',
  'woody',
  'from',
  'their',
  'owner',
  '',
  'the',
  'duo',
  'eventually',
  'learns',
  'to',
  'put',
  'aside',
  'their',
  'differences',
  ''],
 ['jumanji',
  'when',
  'siblings',
  'judy',
  'and',
  'peter',
  'discover',
  'an',
  'enchanted',
  'board',
  'game',
  'that',
  'opens',
  'the',
  'door',
  'to',
  'a',
  'magical',
  'world',
  '',
  'they',
  'unwittingly',
  'invite',
  'alan',
  '',
  '',
  'an',
  'adult',
  'who',
  's',
  'been',
  'trapped',
  'inside',
  'the',
  'game',
  'for',
  '',
  '',
  'years',
  '',
  '',
  'into',
  'their',
  'living',
  'room',
  '',
  'alan',
  's',
  'only',
  'hope',
  'for',
  'freedom',
  'is',
  'to',
  'finish',
  'the',
  'game',
  '',
  'which',
  'proves',
  'risky',
  'as',
  'all',
  'three',
  'find',
  'themselves',
  'running',
  'from',
  'giant',
  'rhinoceroses',
  '',
  'evil',
  'monkeys',
  'and',
  'other',
  'terrifying',
  'creatures',
  ''],
 ['grumpier',
  'old',
  'men',
  'a',
  'family',
  'wedding',
  'reignites',
  'the',
  'ancient',
  'feud',
  'between',
  'next',
  'door',
  'neighbors',
  'and',
  'fishing',
  'buddies',
  'john',
  'and',
  'max',
  '',
  'meanwhile',
  '',
  'a',
  'sultry',
  'italian',
  'divorc',
  'e',
  'opens',
  'a',
  'restaurant',
  'at',
  'the',
  'local',
  'bait',
  'shop',
  '',
  'alarming',
  'the',
  'locals',
  'who',
  'worry',
  'she',
  'll',
  'scare',
  'the',
  'fish',
  'away',
  '',
  'but',
  'she',
  's',
  'less',
  'interested',
  'in',
  'seafood',
  'than',
  'she',
  'is',
  'in',
  'cooking',
  'up',
  'a',
  'hot',
  'time',
  'with',
  'max',
  ''],
 ['waiting',
  'to',
  'exhale',
  'cheated',
  'on',
  '',
  'mistreated',
  'and',
  'stepped',
  'on',
  '',
  'the',
  'women',
  'are',
  'holding',
  'their',
  'breath',
  '',
  'waiting',
  'for',
  'the',
  'elusive',
  '',
  'good',
  'man',
  '',
  'to',
  'break',
  'a',
  'string',
  'of',
  'less',
  'than',
  'stellar',
  'lovers',
  '',
  'friends',
  'and',
  'confidants',
  'vannah',
  '',
  'bernie',
  '',
  'glo',
  'and',
  'robin',
  'talk',
  'it',
  'all',
  'out',
  '',
  'determined',
  'to',
  'find',
  'a',
  'better',
  'way',
  'to',
  'breathe',
  ''],
 ['father',
  'of',
  'the',
  'bride',
  'part',
  'ii',
  'just',
  'when',
  'george',
  'banks',
  'has',
  'recovered',
  'from',
  'his',
  'daughter',
  's',
  'wedding',
  '',
  'he',
  'receives',
  'the',
  'news',
  'that',
  'she',
  's',
  'pregnant',
  '',
  '',
  'and',
  'that',
  'george',
  's',
  'wife',
  '',
  'nina',
  '',
  'is',
  'expecting',
  'too',
  '',
  'he',
  'was',
  'planning',
  'on',
  'selling',
  'their',
  'home',
  '',
  'but',
  'that',
  's',
  'a',
  'plan',
  'that',
  '',
  '',
  'like',
  'george',
  '',
  '',
  'will',
  'have',
  'to',
  'change',
  'with',
  'the',
  'arrival',
  'of',
  'both',
  'a',
  'grandchild',
  'and',
  'a',
  'kid',
  'of',
  'his',
  'own',
  '']]

In [9]:
from collections import Counter
from sklearn.feature_extraction.text import TfidfTransformer

max_words = 10000
def get_tfidf_matrix(title_overviews):
    '''
    args:
        title_overviews: list(list(str)), list of list of string representing each document
    return:
        tfidf_matrix: np.array, TF-IDF matrix
    '''
    # get counts of the word of matrix
    counter = Counter(np.hstack(title_overviews))

    # create mapping from word to index, get the most frequent 10000 words    
    word2index =  {unique_word: idx for idx, (unique_word, count) in 
                   enumerate(sorted(counter.items(), key=lambda x:-x[1])) if idx < max_words}

    #initialize empty count matrix
    count_matrix = np.zeros([len(title_overviews), max_words], dtype=np.int32)
    
    # start counting terms
    for idx, title_overview in enumerate(title_overviews):
        for word in title_overview:
            if word in word2index:
                count_matrix[idx][word2index[word]] += 1
    # tfidf
    transformer = TfidfTransformer()
    tfidf_matrix = transformer.fit_transform(count_matrix)
    
    # convert to numpy array for easier operation
    return tfidf_matrix.toarray()

tfidf_matrix = get_tfidf_matrix(title_overviews)
tfidf_matrix.shape

(45466, 10000)

In [12]:
# TF-IDF vectors have been normalized
(tfidf_matrix ** 2).sum(1)

array([1., 1., 1., ..., 1., 1., 1.])

In [9]:
def get_most_similar_items(tfidf_matrix, idx, top_n):
    '''
    args:
        tfidf_matrix: np.array, TF-IDF matrix
        idx: int, index of the movie
        top_n: int, how many recommendation to be returned
    return:
        most_similar_items: np.array, a list of  item index
        
    '''
    
    # 1d array (max_words, )
    tfidf_matrix[idx]
    
    # 2d array (num_movies, max_words)
    tfidf_matrix
    
    # compute dot product to obtain similarity scores, output shape: (num_movies, )
    scores = np.matmul(tfidf_matrix, tfidf_matrix[idx].reshape(-1,1)).reshape(-1)

    # obtain the highest score items, flip because arg
    most_similar_items = np.flip(np.argsort(scores))
    
    # filter out the item itself
    most_similar_items = most_similar_items[most_similar_items != idx][:top_n]
    
    return most_similar_items

In [16]:
df.loc[df.title.str.contains('Harry Potter'),:]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
4766,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://harrypotter.warnerbros.com/harrypottera...,671,tt0241527,en,Harry Potter and the Philosopher's Stone,Harry Potter has lived under the stairs at his...,...,2001-11-16,9.764756e+08,152.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Let the Magic Begin.,Harry Potter and the Philosopher's Stone,False,7.5,7188.0
5678,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",100000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,672,tt0295297,en,Harry Potter and the Chamber of Secrets,"Ignoring threats to his life, Harry returns to...",...,2002-11-13,8.766885e+08,161.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hogwarts is back in session.,Harry Potter and the Chamber of Secrets,False,7.4,5966.0
7725,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",130000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,673,tt0304141,en,Harry Potter and the Prisoner of Azkaban,"Harry, Ron and Hermione return to Hogwarts for...",...,2004-05-31,7.898046e+08,141.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Something wicked this way comes.,Harry Potter and the Prisoner of Azkaban,False,7.7,6037.0
10554,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://harrypotter.warnerbros.com/,674,tt0330373,en,Harry Potter and the Goblet of Fire,"Harry starts his fourth year at Hogwarts, comp...",...,2005-11-05,8.959210e+08,157.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Dark And Difficult Times Lie Ahead.,Harry Potter and the Goblet of Fire,False,7.5,5758.0
11927,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.harrypotterorderofthephoenix.com/,675,tt0373889,en,Harry Potter and the Order of the Phoenix,Returning for his fifth year of study at Hogwa...,...,2007-06-28,9.382127e+08,138.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Evil Must Be Confronted.,Harry Potter and the Order of the Phoenix,False,7.4,5633.0
13893,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://harrypotter.warnerbros.com/harrypottera...,767,tt0417741,en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",...,2009-07-07,9.339592e+08,153.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,False,7.4,5435.0
16128,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.harrypotter.com,12444,tt0926084,en,Harry Potter and the Deathly Hallows: Part 1,"Harry, Ron and Hermione walk away from their l...",...,2010-10-17,9.543059e+08,146.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Way… One Fate… One Hero.,Harry Potter and the Deathly Hallows: Part 1,False,7.5,5708.0
17437,False,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://www.harrypotter.com,12445,tt1201607,en,Harry Potter and the Deathly Hallows: Part 2,"Harry, Ron and Hermione continue their quest t...",...,2011-07-07,1.342000e+09,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It all ends here.,Harry Potter and the Deathly Hallows: Part 2,False,7.9,6141.0

In [11]:
df.iloc[get_most_similar_items(tfidf_matrix, 4766, 10)].title.tolist()

['Harry Potter and the Goblet of Fire',
 'Harry Potter and the Deathly Hallows: Part 2',
 'Harry Potter and the Deathly Hallows: Part 1',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Chamber of Secrets',
 'Luv',
 'Harry Potter and the Prisoner of Azkaban',
 'Six Ways to Sunday',
 "Harry, He's Here To Help",
 'Cherry, Harry & Raquel!']

In [12]:
df.loc[df.title.str.contains('X-Men'),:]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
3671,False,"{'id': 748, 'name': 'X-Men Collection', 'poste...",75000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",NaN,36657,tt0120903,en,X-Men,"Two mutants, Rogue and Wolverine, come to a pr...",...,2000-07-13,296339527.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Evolution Begins,X-Men,False,6.8,4172.0
10973,False,"{'id': 748, 'name': 'X-Men Collection', 'poste...",210000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",NaN,36668,tt0376994,en,X-Men: The Last Stand,"When a cure is found to treat mutations, lines...",...,2006-05-24,459359555.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Take a Stand,X-Men: The Last Stand,False,6.3,3581.0
13635,False,"{'id': 453993, 'name': 'The Wolverine Collecti...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.x-menorigins.com/,2080,tt0458525,en,X-Men Origins: Wolverine,"After seeking to live a normal life, Logan set...",...,2009-04-28,373062864.0,107.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Witness the Origin.,X-Men Origins: Wolverine,False,6.2,4086.0
17217,False,"{'id': 748, 'name': 'X-Men Collection', 'poste...",160000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.x-menfirstclassmovie.com/,49538,tt1270798,en,X-Men: First Class,Before Charles Xavier and Erik Lensherr took t...,...,2011-05-24,353624124.0,132.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,Witness the moment that will change our world.,X-Men: First Class,False,7.1,5252.0
23359,False,"{'id': 748, 'name': 'X-Men Collection', 'poste...",250000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.x-menmovies.com/,127585,tt1877832,en,X-Men: Days of Future Past,The ultimate X-Men ensemble fights a war for t...,...,2014-05-15,747862775.0,131.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"To save the future, they must alter the past",X-Men: Days of Future Past,False,7.5,6155.0
26569,False,"{'id': 748, 'name': 'X-Men Collection', 'poste...",178000000,"[{'id': 878, 'name': 'Science Fiction'}]",http://www.foxmovies.com/movies/x-men-apocalypse,246655,tt3385516,en,X-Men: Apocalypse,After the re-emergence of the world's first mu...,...,2016-05-18,543934787.0,144.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Only the strong will survive,X-Men: Apocalypse,False,6.4,4831.0

In [13]:
df.iloc[get_most_similar_items(tfidf_matrix, 3671, 10)].title.tolist()

['Wojaczek',
 'X-Men: The Last Stand',
 'X-Men: First Class',
 'X-Men: Apocalypse',
 'X-Men: Days of Future Past',
 'X: Past Is Present',
 'X: The Unheard Music',
 'X-Men Origins: Wolverine',
 'We Are X',
 'Journey to Planet X']

In [14]:
import json
df['genres'] = df.genres.apply(lambda x: [ dic['name'] for dic in json.loads(x.replace("'",'"')) ])
df.genres.head()

0     [Animation, Comedy, Family]
1    [Adventure, Fantasy, Family]
2               [Romance, Comedy]
3        [Comedy, Drama, Romance]
4                        [Comedy]
Name: genres, dtype: object

In [15]:
# utilize more data
def get_title_overviews_improved(df):    
    # extract titles and overviews
    title_overviews = df.apply(lambda x:x['title'].lower() +' '+ x['overview'].lower() + ' '.join(x['genres'] * 3), axis=1).values
        
    # text cleaning
    title_overviews = [re.sub(r'[^a-zA-Z ]+', ' ', title_overview ) for title_overview in  title_overviews]
    
    # split to list
    title_overviews = [title_overview.split(' ') for title_overview in  title_overviews]
    
    
    return title_overviews
title_overviews = get_title_overviews_improved(df)
title_overviews[:5]

[['toy',
  'story',
  'led',
  'by',
  'woody',
  '',
  'andy',
  's',
  'toys',
  'live',
  'happily',
  'in',
  'his',
  'room',
  'until',
  'andy',
  's',
  'birthday',
  'brings',
  'buzz',
  'lightyear',
  'onto',
  'the',
  'scene',
  '',
  'afraid',
  'of',
  'losing',
  'his',
  'place',
  'in',
  'andy',
  's',
  'heart',
  '',
  'woody',
  'plots',
  'against',
  'buzz',
  '',
  'but',
  'when',
  'circumstances',
  'separate',
  'buzz',
  'and',
  'woody',
  'from',
  'their',
  'owner',
  '',
  'the',
  'duo',
  'eventually',
  'learns',
  'to',
  'put',
  'aside',
  'their',
  'differences',
  'Animation',
  'Comedy',
  'Family',
  'Animation',
  'Comedy',
  'Family',
  'Animation',
  'Comedy',
  'Family'],
 ['jumanji',
  'when',
  'siblings',
  'judy',
  'and',
  'peter',
  'discover',
  'an',
  'enchanted',
  'board',
  'game',
  'that',
  'opens',
  'the',
  'door',
  'to',
  'a',
  'magical',
  'world',
  '',
  'they',
  'unwittingly',
  'invite',
  'alan',
  '',
  '',
  'an',
  'adult',
  'who',
  's',
  'been',
  'trapped',
  'inside',
  'the',
  'game',
  'for',
  '',
  '',
  'years',
  '',
  '',
  'into',
  'their',
  'living',
  'room',
  '',
  'alan',
  's',
  'only',
  'hope',
  'for',
  'freedom',
  'is',
  'to',
  'finish',
  'the',
  'game',
  '',
  'which',
  'proves',
  'risky',
  'as',
  'all',
  'three',
  'find',
  'themselves',
  'running',
  'from',
  'giant',
  'rhinoceroses',
  '',
  'evil',
  'monkeys',
  'and',
  'other',
  'terrifying',
  'creatures',
  'Adventure',
  'Fantasy',
  'Family',
  'Adventure',
  'Fantasy',
  'Family',
  'Adventure',
  'Fantasy',
  'Family'],
 ['grumpier',
  'old',
  'men',
  'a',
  'family',
  'wedding',
  'reignites',
  'the',
  'ancient',
  'feud',
  'between',
  'next',
  'door',
  'neighbors',
  'and',
  'fishing',
  'buddies',
  'john',
  'and',
  'max',
  '',
  'meanwhile',
  '',
  'a',
  'sultry',
  'italian',
  'divorc',
  'e',
  'opens',
  'a',
  'restaurant',
  'at',
  'the',
  'local',
  'bait',
  'shop',
  '',
  'alarming',
  'the',
  'locals',
  'who',
  'worry',
  'she',
  'll',
  'scare',
  'the',
  'fish',
  'away',
  '',
  'but',
  'she',
  's',
  'less',
  'interested',
  'in',
  'seafood',
  'than',
  'she',
  'is',
  'in',
  'cooking',
  'up',
  'a',
  'hot',
  'time',
  'with',
  'max',
  'Romance',
  'Comedy',
  'Romance',
  'Comedy',
  'Romance',
  'Comedy'],
 ['waiting',
  'to',
  'exhale',
  'cheated',
  'on',
  '',
  'mistreated',
  'and',
  'stepped',
  'on',
  '',
  'the',
  'women',
  'are',
  'holding',
  'their',
  'breath',
  '',
  'waiting',
  'for',
  'the',
  'elusive',
  '',
  'good',
  'man',
  '',
  'to',
  'break',
  'a',
  'string',
  'of',
  'less',
  'than',
  'stellar',
  'lovers',
  '',
  'friends',
  'and',
  'confidants',
  'vannah',
  '',
  'bernie',
  '',
  'glo',
  'and',
  'robin',
  'talk',
  'it',
  'all',
  'out',
  '',
  'determined',
  'to',
  'find',
  'a',
  'better',
  'way',
  'to',
  'breathe',
  'Comedy',
  'Drama',
  'Romance',
  'Comedy',
  'Drama',
  'Romance',
  'Comedy',
  'Drama',
  'Romance'],
 ['father',
  'of',
  'the',
  'bride',
  'part',
  'ii',
  'just',
  'when',
  'george',
  'banks',
  'has',
  'recovered',
  'from',
  'his',
  'daughter',
  's',
  'wedding',
  '',
  'he',
  'receives',
  'the',
  'news',
  'that',
  'she',
  's',
  'pregnant',
  '',
  '',
  'and',
  'that',
  'george',
  's',
  'wife',
  '',
  'nina',
  '',
  'is',
  'expecting',
  'too',
  '',
  'he',
  'was',
  'planning',
  'on',
  'selling',
  'their',
  'home',
  '',
  'but',
  'that',
  's',
  'a',
  'plan',
  'that',
  '',
  '',
  'like',
  'george',
  '',
  '',
  'will',
  'have',
  'to',
  'change',
  'with',
  'the',
  'arrival',
  'of',
  'both',
  'a',
  'grandchild',
  'and',
  'a',
  'kid',
  'of',
  'his',
  'own',
  'Comedy',
  'Comedy',
  'Comedy']]

In [16]:
tfidf_matrix = get_tfidf_matrix(title_overviews)

In [17]:
# harry potter
df.iloc[get_most_similar_items(tfidf_matrix, 4766, 10)].title.tolist()

['Harry Potter and the Goblet of Fire',
 'Harry Potter and the Deathly Hallows: Part 2',
 'Harry Potter and the Deathly Hallows: Part 1',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Prisoner of Azkaban',
 'Harry Potter and the Half-Blood Prince',
 'Six Ways to Sunday',
 'Luv',
 'Cherry, Harry & Raquel!']

In [18]:
# X-Men
df.iloc[get_most_similar_items(tfidf_matrix, 3671, 10)].title.tolist()

['X-Men: The Last Stand',
 'X-Men Origins: Wolverine',
 'X-Men: First Class',
 'X-Men: Days of Future Past',
 'Avatar 2',
 'Ultraman',
 'X2',
 '2012: Ice Age',
 'Robo Warriors',
 'Rogue One: A Star Wars Story']